/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hmwapp;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void testEqualty() {
        int[] arr1 = {2, 2, 5, 5};
        int[] arr2 = {2, 2};
        Integer i = 5;
        assertTrue(App.meanCompareOfTwoArrays(arr1, arr2, i, 3));


    }


    @Test
    void testWithZeros() {
        int[] arr1 = {0, 0, 0, 0};
        int[] arr2 = {0, 0, 0, 0, 0, 0, 0};
        Integer i = 5;
        assertTrue(App.meanCompareOfTwoArrays(arr1, arr2, i, 0));


    }

    @Test
    void testEmptyArrays() {
        int[] arr1 = new int[5];
        int[] arr2 = new int[5];
        Integer i = 5;
        assertTrue(App.meanCompareOfTwoArrays(arr1, arr2, i, 0));


    }

    @Test
    void testFalseCase() {
        int[] arr1 = {10, 22, 21, 3, 12};
        int[] arr2 = {2, 67};
        Integer i = 5;
        assertFalse(App.meanCompareOfTwoArrays(arr1, arr2, i, 10));


    }

    @Test
    void testHugeNumbers() {
        int[] arr1 = {1053, 223, 251, 343, 1243};
        int[] arr2 = {2878, 6457, 234};
        Integer i = 5;
        assertTrue(App.meanCompareOfTwoArrays(arr1, arr2, i, 1585));


    }
}
